admin:
  name: "admin"
  email: "changeme@example.com"
  password:
    from_env: ADMIN_PASSWORD

appearance:
  name: "HackHerQuest 2026"
  description: "The HackHerQuest 2026 CTF"

theme:
  logo:
    from_file: images/logo.png
  small_icon:
    from_file: images/logo-icon.png
  name: core-beta
  header:
    from_file: html/theme-header.html
  footer:
    from_file: html/theme-footer.html

settings:
  challenge_visibility: private
  account_visibility: private
  score_visibility: private
  registration_visibility: private

accounts:
  #   # Team creation was set to false in production as teams where created ahead of the event,
  #   # thanks to a qualification round.
  team_creation: false
  team_disbanding: "disabled"
  name_changes: false
  incorrect_submissions_per_minute: 10

time:
  view_after: true
  start: "2026-02-07T13:30:00Z"
  end: "2026-02-07T16:30:00Z"
  freeze: "2026-02-07T16:00:00Z"

legal:
  tos:
    content:
      from_file: md/tos.md

# If set to 'teams', make sure to decide on the team_creation setting below.
mode: teams

pages:
  additional:
    - title: Getting Started
      route: getting-started
      format: markdown
      content:
        from_file: md/getting-started.md
    - title: "Home"
      route: "index"
      content:
        from_file: html/index.html
      # content: |
      # <script>window.location.href = "/challenges";</script>
# uploads:
#   - file:
#       from_file: images/nbc.png
#     location: images/nbc.png
#   - file:
#       from_file: images/pec-white.png
#     location: images/pec-white.png
#   - file:
#       from_file: images/pec.png
#     location: images/pec.png
#   - file:
#       from_file: images/rm-pro-white.svg
#     location: images/rm-pro-white.svg
#   - file:
#       from_file: images/rm-pro.svg
#     location: images/rm-pro.svg
#   - file:
#       from_file: images/synacktiv-white.png
#     location: images/synacktiv-white.png
#   - file:
#       from_file: images/synacktiv.png
#     location: images/synacktiv.png
