admin:
  name: "admin"
  email: "changeme@example.com"
  password:
    from_env: ADMIN_PASSWORD

appearance:
  name: "HackHerQuest 2026"
  description: "The HackHerQuest 2026 CTF"

theme:
  logo:
    from_file: images/logo.png
  small_icon:
    from_file: images/logo-icon.png
  name: core-beta
  header:
    from_file: html/theme-header.html
  footer:
    from_file: html/theme-footer.html

settings:
  challenge_visibility: private
  account_visibility: private
  score_visibility: private
  registration_visibility: private

accounts:
  #   # Team creation was set to false in production as teams where created ahead of the event,
  #   # thanks to a qualification round.
  team_creation: false
  team_disbanding: "disabled"
  team_size: 4
  name_changes: false
  incorrect_submissions_per_minute: 20

challenges:
  view_self_submissions: false
  max_attempts_behavior: "timeout"
  max_attempts_timeout: 60
  hints_free_public_access: false
  challenge_ratings: "disabled"

time:
  view_after: true
  start: "1770471000"
  end: "1770481800"
  freeze: "1770480000"

legal:
  tos:
    content:
      from_file: md/tos.md

# If set to 'teams', make sure to decide on the team_creation setting below.
mode: teams

pages:
  additional:
    - title: "Home"
      route: "index"
      format: html
      content:
        from_file: html/index.html
