configs:
  services-yml:
    file: ./services.yml
  traefik-yml:
    file: ./traefik.yml

services:
  reverse-proxy:
    image: traefik:v2.11
    configs:
      - source: services-yml
        target: /etc/traefik/services.yml
      - source: traefik-yml
        target: /etc/traefik/traefik.yml
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
    ports:
      # The HTTP port
      - "80:80"
      # HTTPS also
      - "443:443"
      # publish The Web UI (enabled by --api.insecure=true)
      # on a public port, uncomment to be able to reach it without DNS
      # but only for testing purposes!
    #      - "8080:8080"
    volumes:
      # Add Docker socket as a mounted volume, so that Traefik can read the labels of other services
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # acme.json for le challenges
      - acme-data:/letsencrypt
    networks:
      - traefik
      - net
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 64M
      placement:
        constraints:
          - node.labels.type == manager

volumes:
  acme-data:

networks:
  traefik:
    external: true
  net:
    external: true
