- name: Setup-CTF
  hosts: ctf
  remote_user: root
  become: true
  vars_files:
    - .env.yml

  vars:
    pip_install_packages:
      - name: docker

  environment:
    NEEDRESTART_MODE: automatically

  pre_tasks:
    - name: Wait for cloud-init / user-data to finish
      # https://serverfault.com/a/1021022
      ansible.builtin.command: cloud-init status --wait
      changed_when: false
    - name: Populate Apt's Cache with package definitions to avoid "no such package" errors
      # https://github.com/geerlingguy/ansible-role-pip/issues/49#issuecomment-1824708282
      ansible.builtin.apt:
        update_cache: true
  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
# TRAEFIK SETUP
    - name: Copy Traefik configuration files
      ansible.builtin.copy:
        src: "./traefik/"
        dest: "/opt/traefik/"
        owner: root
        group: root
        mode: "0755"

    - name: Create traefik network
      community.docker.docker_network:
        name: traefik
        state: present
        driver: bridge

    - name: Substitute environment variables in traefik.yml
      ansible.builtin.shell: |
        envsubst < /opt/traefik/traefik.yml > /opt/traefik/traefik.yml.tmp
        mv /opt/traefik/traefik.yml.tmp /opt/traefik/traefik.yml
      environment:
        DOMAIN: "{{ CTF_DOMAIN }}"
        EMAIL: "{{ CERT_EMAIL }}"
      changed_when: true

    - name: Build and start Traefik
      community.docker.docker_compose_v2:
        project_src: /opt/traefik
        state: present

# CTFD SETUP
    - name: Copy CTFd configuration files
      ansible.builtin.copy:
        src: "./ctfd/"
        dest: "/opt/ctfd/"
        owner: root
        group: root
        mode: "0755"

    - name: Copy CTFd plugins
      ansible.builtin.copy:
        src: "../config/ctfd-plugins/"
        dest: "/opt/ctfd/CTFd/plugins/"
        owner: root
        group: root
        mode: "0755"

    - name: Copy ctfd-setup files
      ansible.builtin.copy:
        src: "../config/ctfd-setup/"
        dest: "/opt/ctfd/ctfd-setup/"
        owner: root
        group: root
        mode: "0755"

    - name: Substitute environment variables in docker-compose.yml
      ansible.builtin.shell: |
        envsubst < /opt/ctfd/docker-compose.yml > /opt/ctfd/docker-compose.yml.tmp
        mv /opt/ctfd/docker-compose.yml.tmp /opt/ctfd/docker-compose.yml
      environment:
        DOMAIN: "{{ CTF_DOMAIN }}"
        SECRET_KEY: "{{ SECRET_KEY }}"
        ADMIN_PASS: "{{ ADMIN_PASS }}"
        ADMIN_TOKEN: "{{ ADMIN_TOKEN }}"
      changed_when: true

    - name: Build and start CTFd docker
      community.docker.docker_compose_v2:
        project_src: /opt/ctfd
        state: present

# REGISTRY SETUP
    - name: Copy Registry configuration files
      ansible.builtin.copy:
        src: "./registry/"
        dest: "/opt/registry/"
        owner: root
        group: root
        mode: "0755"

    - name: Substitute environment variables in docker-compose.yml
      ansible.builtin.shell: |
        envsubst < /opt/registry/docker-compose.yml > /opt/registry/docker-compose.yml.tmp
        mv /opt/registry/docker-compose.yml.tmp /opt/registry/docker-compose.yml
      environment:
        DOMAIN: "registry.{{ CTF_DOMAIN }}"
      changed_when: true

    - name: Create registry htpasswd file
      community.docker.docker_container:
        name: htpasswd_generator
        image: httpd:2
        command: htpasswd -Bbn {{ REGISTRY_USER }} {{ REGISTRY_PASS }}
        state: started
        auto_remove: true
      register: htpasswd_output

    - name: Save htpasswd file
      ansible.builtin.copy:
        content: "{{ htpasswd_output.stdout }}"
        dest: /opt/registry/auth/htpasswd
        owner: root
        group: root
        mode: "0644"

    - name: Build and start Registry docker
      community.docker.docker_compose_v2:
        project_src: /opt/registry
        state: present
