- name: CTF - Setup
  hosts: ctf
  remote_user: root
  become: true
  vars_files:
    - .env.yml
  tags:
    - setup

  vars:
    pip_install_packages:
      - name: docker

  environment:
    NEEDRESTART_MODE: automatically

  pre_tasks:
    - name: Wait for cloud-init / user-data to finish
      # https://serverfault.com/a/1021022
      ansible.builtin.command: cloud-init status --wait
      changed_when: false
    - name: Populate Apt's Cache with package definitions to avoid "no such package" errors
      # https://github.com/geerlingguy/ansible-role-pip/issues/49#issuecomment-1824708282
      ansible.builtin.apt:
        update_cache: true
  roles:
    - geerlingguy.pip
    - geerlingguy.docker

- name: CTF - CTFd setup
  hosts: ctf
  remote_user: root
  become: true
  vars_files:
    - .env.yml

  tasks:
    - name: Install jsondiff for docker_stack module
      ansible.builtin.pip:
        name: jsondiff
        executable: pip3

    - name: Set ctf label
      community.docker.docker_node:
        hostname: "{{ ansible_hostname }}"
        role: manager
        labels:
          type: ctf
      delegate_to: "{{ groups['manager'][0] }}"

    # TRAEFIK SETUP
    - name: Set placement variable
      ansible.builtin.set_fact:
        placement: ctf

    - name: Setup Traefik for the manager node
      ansible.builtin.import_tasks: traefik/ansible.yml

    - name: Ensure CTFd directory exists
      ansible.builtin.file:
        path: "/opt/ctfd"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Copy CTFd configuration files
      ansible.posix.synchronize:
        src: "./ctfd/"
        dest: "/opt/ctfd/"
        recursive: true

    - name: Ensure CTFd plugin directory exists
      ansible.builtin.file:
        path: "/opt/ctfd/CTFd/plugins"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Copy CTFd plugins
      ansible.posix.synchronize:
        src: "../config/ctfd/"
        dest: "/opt/ctfd/CTFd/"
        recursive: true

    - name: Ensure ctfd-setup directory exists
      ansible.builtin.file:
        path: "/opt/ctfd/ctfd-setup"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Copy ctfd-setup files
      ansible.posix.synchronize:
        src: "../config/ctfd-setup/"
        dest: "/opt/ctfd/ctfd-setup/"
        recursive: true

    - name: Substitute environment variables in docker-compose.yml
      ansible.builtin.shell: |
        envsubst < /opt/ctfd/docker-compose.yml > /opt/ctfd/docker-compose.yml.tmp
        mv /opt/ctfd/docker-compose.yml.tmp /opt/ctfd/docker-compose.yml
      environment:
        DOMAIN: "{{ CTF_DOMAIN }}"
        SECRET_KEY: "{{ SECRET_KEY }}"
        ADMIN_PASS: "{{ ADMIN_PASS }}"
        ADMIN_TOKEN: "{{ ADMIN_TOKEN }}"
      changed_when: true

    - name: Build and start CTFd docker
      community.docker.docker_stack:
        compose: /opt/ctfd/docker-compose.yml
        state: present
        name: ctfd
